const Contact = require('../../contacts/models/Contact.model');
const Communication = require('../../communications/models/Communication.model');
const Task = require('../../tasks/models/Task.model');
const { sendEmailWithDevFallback } = require('../../../shared/utils/email');
const notificationService = require('../../notifications/services/notification.service');

const INACTIVITY_DAYS = 7;
const MS_PER_DAY = 24 * 60 * 60 * 1000;

const automationService = {
  touchContactActivity: async (contactId) => {
    if (!contactId) return;
    await Contact.findByIdAndUpdate(contactId, { lastActivityAt: new Date() });
  },

  sendCustomerWelcomeEmail: async (contact, req) => {
    if (!contact?.email) {
      return { sent: false, reason: 'Contact has no email address' };
    }

    if (contact.welcomeEmailSentAt) {
      return { sent: false, reason: 'Welcome email already sent', skipped: true };
    }

    const welcomeHtml = `
      <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#334155">
        <h2 style="color:#0f172a">Welcome, ${contact.firstName}!</h2>
        <p>Thank you for becoming a customer. We're excited to work with you.</p>
        <p>Your dedicated team is here to help with anything you need. We'll be in touch soon.</p>
        <p style="margin-top:24px;color:#64748b;font-size:13px">CRM Management System</p>
      </div>
    `;

    try {
      const delivery = await sendEmailWithDevFallback({
        to: contact.email,
        toName: contact.firstName,
        subject: 'Welcome — We\'re glad to have you!',
        html: welcomeHtml,
      });

      await Contact.findByIdAndUpdate(contact._id, { welcomeEmailSentAt: new Date() });

      if (req?.user?._id) {
        await Communication.create({
          type: 'email',
          subject: 'Welcome — We\'re glad to have you!',
          body: `Automated welcome email sent to ${contact.email}`,
          contact: contact._id,
          userId: req.user._id,
          direction: 'outbound',
          emailTo: delivery.intendedTo,
          emailStatus: 'sent',
          metadata: {
            automated: true,
            welcomeEmail: true,
            deliveredTo: delivery.deliveredTo,
            redirected: delivery.redirected,
          },
        });
      }

      return {
        sent: true,
        to: delivery.intendedTo,
        deliveredTo: delivery.deliveredTo,
        redirected: delivery.redirected,
        message: delivery.redirected
          ? `Welcome email delivered to your account inbox (intended for ${delivery.intendedTo})`
          : `Welcome email sent to ${delivery.intendedTo}`,
      };
    } catch (err) {
      if (req?.user?._id) {
        await Communication.create({
          type: 'email',
          subject: 'Welcome — We\'re glad to have you!',
          body: `Automated welcome email failed for ${contact.email}: ${err.message}`,
          contact: contact._id,
          userId: req.user._id,
          direction: 'outbound',
          emailTo: contact.email,
          emailStatus: 'failed',
          metadata: { automated: true, welcomeEmail: true, error: err.message },
        }).catch(() => {});
      }

      console.error('[Automation] Welcome email failed:', err.message);
      return { sent: false, reason: err.message, to: contact.email };
    }
  },

  notifyLeadAssigned: async (contact, assigneeId, actorId) => {
    if (!assigneeId || !contact) return;
    if (actorId && assigneeId.toString() === actorId.toString()) return;

    await notificationService.notifyUser({
      userId: assigneeId,
      title: 'New Lead Assigned',
      message: `${contact.fullName || contact.firstName} has been assigned to you`,
      type: 'lead',
      link: '/contacts',
      metadata: { contactId: contact._id?.toString() },
      skipUserId: actorId,
    });
  },

  runFollowUpAutomation: async () => {
    const cutoff = new Date(Date.now() - INACTIVITY_DAYS * MS_PER_DAY);

    const inactiveCustomers = await Contact.find({
      isActive: true,
      type: 'customer',
      lastActivityAt: { $lte: cutoff },
      $or: [
        { lastFollowUpAt: { $exists: false } },
        { lastFollowUpAt: null },
        { lastFollowUpAt: { $lte: cutoff } },
      ],
    }).populate('assignedTo createdBy');

    let created = 0;

    for (const contact of inactiveCustomers) {
      const existingTask = await Task.findOne({
        contact: contact._id,
        type: 'follow_up',
        status: { $in: ['pending', 'in_progress'] },
        'metadata.autoGenerated': true,
      });

      if (existingTask) continue;

      const assignee = contact.assignedTo?._id || contact.createdBy?._id || contact.createdBy;
      if (!assignee) continue;

      const dueDate = new Date(Date.now() + MS_PER_DAY);
      const task = await Task.create({
        title: `Follow-up: ${contact.firstName} ${contact.lastName}`,
        description: `No customer activity for ${INACTIVITY_DAYS}+ days. Reach out to re-engage.`,
        type: 'follow_up',
        priority: 'high',
        status: 'pending',
        dueDate,
        reminderAt: new Date(),
        assignedTo: assignee,
        createdBy: assignee,
        contact: contact._id,
        metadata: { autoGenerated: true, reason: 'inactive_customer' },
      });

      await Contact.findByIdAndUpdate(contact._id, { lastFollowUpAt: new Date() });

      await notificationService.notifyUser({
        userId: assignee,
        title: 'Follow-up Reminder',
        message: `${contact.firstName} ${contact.lastName} — no activity for ${INACTIVITY_DAYS} days`,
        type: 'task',
        link: '/tasks',
        metadata: { taskId: task._id.toString(), contactId: contact._id.toString() },
      });

      created += 1;
    }

    if (created > 0) {
      console.log(`[Automation] Created ${created} follow-up reminder(s)`);
    }

    return { checked: inactiveCustomers.length, created };
  },

  syncContactLastActivity: async (contactId) => {
    if (!contactId) return;

    const [latestComm] = await Communication.find({ contact: contactId })
      .sort('-createdAt')
      .limit(1)
      .select('createdAt');

    const contact = await Contact.findById(contactId);
    if (!contact) return;

    const candidates = [contact.updatedAt, contact.createdAt, latestComm?.createdAt].filter(Boolean);
    const lastActivityAt = new Date(Math.max(...candidates.map((d) => new Date(d).getTime())));

    await Contact.findByIdAndUpdate(contactId, { lastActivityAt });
    return lastActivityAt;
  },
};

module.exports = automationService;
